// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "translation": {
    "app": {
      "auth": {
        "required": "Please sign in to continue."
      },
      "brandName": "LITTLE RED BOOK",
      "dashboard": {
        "title": "Dashboard"
      },
      "header": {
        "title": "Documents"
      },
      "languageSwitch": {
        "label": "Change language"
      },
      "nav": {
        "aiAssistant": "AI Intelligence",
        "aiRankings": "Recommended rankings",
        "autoAnalysis": "Auto analysis",
        "dashboard": "Dashboard",
        "featuredMessages": "Featured messages",
        "gameCenter": "Game center",
        "gameHistory": "History",
        "globalConfig": "Global config",
        "groupList": "Group list",
        "groupManagement": "Group management",
        "groupUsers": "Group users",
        "liveMonitor": "Live monitor",
        "permissionManagement": "Permission management",
        "roastAlerts": "Roast alerts",
        "systemSettings": "System settings"
      },
      "settings": {
        "actions": {
          "cancel": "Cancel",
          "retry": "Retry"
        },
        "description": "Manage how you sign in and keep access to your account protected.",
        "passkeys": {
          "add": "Add passkey",
          "addDialog": {
            "description": "Name this passkey before starting browser registration.",
            "helper": "Registration is not connected yet.",
            "label": "Passkey name",
            "placeholder": "MacBook Touch ID",
            "submit": "Start setup",
            "title": "Add passkey"
          },
          "delete": {
            "description": "This will remove {{label}} from your account. Deletion is not connected yet.",
            "submit": "Delete",
            "title": "Delete passkey?",
            "trigger": "Delete passkey"
          },
          "description": "Use device biometrics, security keys, or password managers to sign in faster.",
          "empty": {
            "description": "Add a passkey to sign in without typing your password.",
            "title": "No passkeys yet"
          },
          "error": {
            "description": "Refresh the list or try again in a moment.",
            "title": "Passkeys could not be loaded"
          },
          "neverUsed": "Never used",
          "rename": {
            "inputLabel": "Passkey name",
            "save": "Save passkey name",
            "trigger": "Rename passkey"
          },
          "table": {
            "actions": "Actions",
            "created": "Created",
            "id": "ID {{id}}",
            "lastUsed": "Last used",
            "name": "Name"
          },
          "title": "Passkeys"
        },
        "password": {
          "confirmPassword": {
            "label": "Confirm password",
            "placeholder": "Repeat the new password"
          },
          "description": "Set a password for email and password sign-in.",
          "helper": "Use 12 to 72 characters.",
          "newPassword": {
            "label": "New password",
            "placeholder": "Enter a new password"
          },
          "submit": "Update password",
          "title": "Password",
          "update": {
            "errorMessage": "We couldn't update your password. Please check it and try again.",
            "successMessage": "Your password has been saved.",
            "successTitle": "Password updated"
          },
          "validation": {
            "confirmationMax": "Confirmation must be at most 72 characters.",
            "confirmationMin": "Confirmation must be at least 12 characters.",
            "passwordMax": "Password must be at most 72 characters.",
            "passwordMin": "Password must be at least 12 characters.",
            "passwordsMatch": "Passwords must match."
          }
        },
        "title": "Account Settings"
      },
      "userMenu": {
        "account": "Account",
        "billing": "Billing",
        "logOut": "Log out",
        "notifications": "Notifications"
      }
    },
    "auth": {
      "login": {
        "brandName": "MY LITTLE RED BOOK",
        "emailInput": {
          "domain": "@qq.com",
          "placeholder": "123456789",
          "title": "Enter 5 to 13 digits"
        },
        "emailStep": {
          "continue": "Continue",
          "description": "Enter your QQ email to continue.",
          "noAccount": "No account yet? Click here to",
          "qqHint": "Enter your QQ number only. We'll add @qq.com and show your available sign-in options next.",
          "registration": {
            "errorMessage": "We couldn't create your account. Please check the email and try again.",
            "successMessage": "Check your email for the login link.",
            "successTitle": "Account created"
          },
          "signUp": "Sign up",
          "title": "Welcome"
        },
        "fields": {
          "email": "Email",
          "password": "Password"
        },
        "imageAlt": "Abstract wave pattern",
        "languageSwitch": {
          "label": "Change language"
        },
        "legal": {
          "agreement": "By clicking continue, you agree to our <terms>Terms of Service</terms> and <privacy>Privacy Policy</privacy>."
        },
        "methodsStep": {
          "description": "Choose how you want to continue.",
          "emailLink": "Send passwordless login link",
          "passkey": "Sign in with passkey",
          "passwordLogin": {
            "errorMessage": "Please check your email and password",
            "errorTitle": "Login failed"
          },
          "passwordlessLogin": {
            "errorMessage": "Please check your email and try again",
            "errorTitle": "Failed to send",
            "successMessage": "Check your email for the login link",
            "successTitle": "Login link sent"
          },
          "separator": "OR",
          "signIn": "Sign in",
          "title": "Welcome",
          "useDifferentEmail": "Use a different email"
        }
      }
    }
  }
}
