// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "translation": {
    "app": {
      "auth": {
        "required": "Please sign in to continue."
      },
      "brandName": "LITTLE RED BOOK",
      "dashboard": {
        "pageTitle": "Dashboard",
        "title": "Dashboard"
      },
      "errorBoundary": {
        "dashboard": "Go to dashboard",
        "details": "Error details",
        "eyebrow": "Recovery mode",
        "fallback": {
          "description": "An unexpected error occurred. Please try again.",
          "title": "Something went wrong"
        },
        "goBack": "Go back",
        "login": "Go to login",
        "status": {
          "400": {
            "description": "The request was invalid. Please check and try again.",
            "title": "Bad request"
          },
          "401": {
            "description": "Please sign in to access this page.",
            "title": "Sign in required"
          },
          "403": {
            "description": "You don't have permission to view this page.",
            "title": "Access denied"
          },
          "404": {
            "description": "The page you're looking for doesn't exist.",
            "title": "Page not found"
          },
          "500": {
            "description": "Something went wrong on our end. Please try again later.",
            "title": "Server error"
          }
        }
      },
      "groups": {
        "access": {
          "admin": "Admin",
          "member": "Member"
        },
        "actions": {
          "retry": "Retry"
        },
        "description": "Review visible groups, inspect members, and control where DianBot is enabled.",
        "details": {
          "error": {
            "description": "Refresh the group details or try again in a moment.",
            "title": "Group details could not be loaded"
          },
          "noSelection": "Select a group to view details."
        },
        "filters": {
          "access": {
            "admin": "Admin only",
            "all": "All access",
            "member": "Member only"
          },
          "accessLabel": "Filter by permission",
          "searchLabel": "Search groups",
          "searchPlaceholder": "Search name or ID",
          "status": {
            "all": "All status",
            "disabled": "Disabled",
            "enabled": "Enabled"
          },
          "statusLabel": "Filter by status"
        },
        "list": {
          "description": "Find the groups you need and review their bot status at a glance.",
          "empty": {
            "description": "Adjust the filters to find another group.",
            "title": "No groups found"
          },
          "error": {
            "description": "Refresh the list or try again in a moment.",
            "title": "Groups could not be loaded"
          },
          "table": {
            "access": "Access",
            "group": "Group",
            "members": "Members",
            "status": "Status"
          },
          "title": "Groups"
        },
        "members": {
          "count": "{{count}} members",
          "empty": {
            "description": "Adjust the filters to find another member.",
            "title": "No members found"
          },
          "filters": {
            "role": {
              "admin": "Admin",
              "all": "All roles",
              "member": "Member",
              "owner": "Owner",
              "robot": "Bot"
            },
            "roleLabel": "Filter by member role",
            "searchLabel": "Search members",
            "searchPlaceholder": "Search name or QQ ID"
          },
          "pagination": {
            "next": "Next",
            "of": "of",
            "page": "Page",
            "previous": "Previous",
            "total": "{{count}} members"
          },
          "robot": "Bot",
          "roles": {
            "admin": "Admin",
            "member": "Member",
            "owner": "Owner"
          },
          "table": {
            "joined": "Joined",
            "member": "Member",
            "role": "Role"
          },
          "title": "Members"
        },
        "pageTitle": "Group Management",
        "pagination": {
          "next": "Next",
          "of": "of",
          "page": "Page",
          "previous": "Previous",
          "total": "{{count}} groups"
        },
        "settings": {
          "adminOnlyDescription": "Only group admins can change bot availability.",
          "description": "Enable this group to allow bot commands and push notifications.",
          "enabledLabel": "Toggle bot availability",
          "title": "Bot availability",
          "update": {
            "errorMessage": "Could not update group settings. Please try again.",
            "successMessage": "Group settings updated."
          }
        },
        "status": {
          "disabled": "Disabled",
          "enabled": "Enabled"
        },
        "summary": {
          "admin": "Admin",
          "enabled": "Enabled",
          "total": "Total"
        },
        "title": "Group Management"
      },
      "header": {
        "title": "Documents"
      },
      "languageSwitch": {
        "label": "Change language"
      },
      "nav": {
        "aiAssistant": "AI Intelligence",
        "aiRankings": "Recommended rankings",
        "autoAnalysis": "Auto analysis",
        "dashboard": "Dashboard",
        "featuredMessages": "Featured messages",
        "gameCenter": "Game center",
        "gameHistory": "History",
        "globalConfig": "Global config",
        "groupList": "Group list",
        "groupManagement": "Group management",
        "groupUsers": "Group users",
        "groups": "Groups",
        "liveMonitor": "Live monitor",
        "permissionManagement": "Permission management",
        "roastAlerts": "Roast alerts",
        "systemSettings": "System settings"
      },
      "settings": {
        "actions": {
          "cancel": "Cancel",
          "retry": "Retry"
        },
        "description": "Manage sign-in methods, account security, and connected gaming accounts.",
        "pageTitle": "Account Settings",
        "passkeys": {
          "add": "Add passkey",
          "addDialog": {
            "description": "Name this passkey before starting browser registration.",
            "helper": "Name your passkey so you can recognise it later.",
            "label": "Passkey name",
            "placeholder": "MacBook Touch ID",
            "submit": "Start setup",
            "title": "Add passkey"
          },
          "delete": {
            "description": "This will remove {{label}} from your account.",
            "errorMessage": "Could not delete passkey. Please try again.",
            "submit": "Delete",
            "successMessage": "Passkey deleted.",
            "title": "Delete passkey?",
            "trigger": "Delete passkey"
          },
          "description": "Use device biometrics, security keys, or password managers to sign in faster.",
          "empty": {
            "description": "Add a passkey to sign in without typing your password.",
            "title": "No passkeys yet"
          },
          "error": {
            "description": "Refresh the list or try again in a moment.",
            "title": "Passkeys could not be loaded"
          },
          "neverUsed": "Never used",
          "rename": {
            "errorMessage": "Could not rename passkey. Please try again.",
            "inputLabel": "Passkey name",
            "save": "Save passkey name",
            "successMessage": "Passkey renamed.",
            "trigger": "Rename passkey",
            "validation": {
              "required": "Enter a passkey name."
            }
          },
          "table": {
            "actions": "Actions",
            "created": "Created",
            "id": "ID {{id}}",
            "lastUsed": "Last used",
            "name": "Name"
          },
          "title": "Passkeys"
        },
        "password": {
          "confirmPassword": {
            "label": "Confirm password",
            "placeholder": "Repeat the new password"
          },
          "description": "Set a password for email and password sign-in.",
          "helper": "Use 12 to 72 characters.",
          "newPassword": {
            "label": "New password",
            "placeholder": "Enter a new password"
          },
          "submit": "Update password",
          "title": "Password",
          "update": {
            "errorMessage": "We couldn't update your password. Please check it and try again.",
            "successMessage": "Your password has been saved.",
            "successTitle": "Password updated"
          },
          "validation": {
            "confirmationMax": "Confirmation must be at most 72 characters.",
            "confirmationMin": "Confirmation must be at least 12 characters.",
            "passwordMax": "Password must be at most 72 characters.",
            "passwordMin": "Password must be at least 12 characters.",
            "passwordsMatch": "Passwords must match."
          }
        },
        "sections": {
          "accountSecurity": {
            "description": "Update credentials and sign-in methods that protect access to your account.",
            "title": "Account Security"
          },
          "connectedAccounts": {
            "description": "Link external gaming accounts used for status tracking and activity features.",
            "title": "Connected Accounts"
          }
        },
        "steam": {
          "bind": {
            "back": "Back",
            "confirm": "Confirm linking",
            "description": "Enter your 17-digit Steam ID to look up and link your account.",
            "errorMessage": "Could not link Steam account. Please try again.",
            "lookup": "Look up",
            "lookupError": "Could not find a Steam profile for this ID. Please check and try again.",
            "lookupServiceError": "Could not look up this Steam profile right now. Please try again.",
            "steamId": {
              "helper": "Your 17-digit Steam ID starting with 7656.",
              "label": "Steam ID",
              "placeholder": "76561198012345678"
            },
            "successMessage": "Your Steam account has been linked successfully.",
            "successTitle": "Steam account linked",
            "title": "Link Steam Account",
            "trigger": "Link Steam"
          },
          "description": "Link your Steam account to enable game status tracking and notifications.",
          "error": {
            "description": "Try again in a moment.",
            "title": "Steam profile could not be loaded"
          },
          "notBound": {
            "description": "Link your Steam account to see your profile here.",
            "title": "No Steam account linked"
          },
          "playing": "Playing {{game}}",
          "profileLink": "View Steam Profile",
          "state": {
            "away": "Away",
            "busy": "Busy",
            "offline": "Offline",
            "online": "Online",
            "snooze": "Snooze"
          },
          "title": "Steam Account"
        },
        "title": "Account Settings"
      },
      "userMenu": {
        "account": "Account",
        "billing": "Billing",
        "logOut": "Log out",
        "notifications": "Notifications"
      }
    },
    "auth": {
      "flash": {
        "logout": "Logged out",
        "setPassword": "Account created",
        "setPasswordAction": "Settings",
        "setPasswordDescription": "Create a password or passkey in your account settings.",
        "welcome": "Welcome back"
      },
      "login": {
        "brandName": "MY LITTLE RED BOOK",
        "emailInput": {
          "domain": "@qq.com",
          "placeholder": "123456789",
          "title": "Enter 5 to 13 digits"
        },
        "emailStep": {
          "continue": "Continue",
          "description": "Enter your QQ email to continue.",
          "noAccount": "No account yet? Click here to",
          "qqHint": "Enter your QQ number only. We'll add @qq.com and show your available sign-in options next.",
          "registration": {
            "errorMessage": "We couldn't create your account. Please check the email and try again.",
            "successMessage": "Check your email for the login link.",
            "successTitle": "Account created"
          },
          "signUp": "Sign up",
          "title": "Welcome"
        },
        "fields": {
          "email": "Email",
          "password": "Password"
        },
        "imageAlt": "Abstract wave pattern",
        "languageSwitch": {
          "label": "Change language"
        },
        "legal": {
          "agreement": "By clicking continue, you agree to our <terms>Terms of Service</terms> and <privacy>Privacy Policy</privacy>."
        },
        "methodsStep": {
          "description": "Choose how you want to continue.",
          "emailLink": "Send passwordless login link",
          "passkey": "Sign in with passkey",
          "passkeyLogin": {
            "errorMessage": "We couldn't verify your passkey. Please try again or use another method.",
            "errorTitle": "Passkey sign-in failed",
            "successMessage": "Welcome back",
            "successTitle": "Signed in successfully"
          },
          "passwordLogin": {
            "errorMessage": "Please check your email and password",
            "errorTitle": "Login failed",
            "successMessage": "Welcome back",
            "successTitle": "Signed in successfully"
          },
          "passwordlessLogin": {
            "errorMessage": "Please check your email and try again",
            "errorTitle": "Failed to send",
            "successMessage": "Check your email for the login link",
            "successTitle": "Login link sent"
          },
          "separator": "OR",
          "signIn": "Sign in",
          "title": "Welcome",
          "useDifferentEmail": "Use a different email"
        },
        "pageTitle": "Sign In"
      }
    }
  }
}
