// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "translation": {
    "app": {
      "auth": {
        "required": "Please sign in to continue."
      },
      "brandName": "LITTLE RED BOOK",
      "dashboard": {
        "cards": {
          "accounts": {
            "detail": "Engagement is ahead of target",
            "label": "Active accounts",
            "trend": "Retention remains strong"
          },
          "customers": {
            "detail": "Review campaign quality and conversion",
            "label": "New customers",
            "trend": "Customer acquisition dipped"
          },
          "growth": {
            "detail": "Tracking ahead of forecast",
            "label": "Growth rate",
            "trend": "Growth is steady"
          },
          "revenue": {
            "detail": "Trailing 6-month performance",
            "label": "Revenue",
            "trend": "Revenue is up this month"
          }
        },
        "title": "Dashboard"
      },
      "header": {
        "title": "Documents"
      },
      "languageSwitch": {
        "label": "Change language"
      },
      "nav": {
        "aiAssistant": "AI Intelligence",
        "aiRankings": "Recommended rankings",
        "autoAnalysis": "Auto analysis",
        "dashboard": "Dashboard",
        "featuredMessages": "Featured messages",
        "gameCenter": "Game center",
        "gameHistory": "History",
        "globalConfig": "Global config",
        "groupList": "Group list",
        "groupManagement": "Group management",
        "groupUsers": "Group users",
        "liveMonitor": "Live monitor",
        "permissionManagement": "Permission management",
        "roastAlerts": "Roast alerts",
        "systemSettings": "System settings"
      },
      "userMenu": {
        "account": "Account",
        "billing": "Billing",
        "logOut": "Log out",
        "notifications": "Notifications"
      }
    },
    "auth": {
      "login": {
        "brandName": "MY LITTLE RED BOOK",
        "emailInput": {
          "domain": "@qq.com",
          "placeholder": "123456789",
          "title": "Enter 5 to 13 digits"
        },
        "emailStep": {
          "continue": "Continue",
          "description": "Enter your QQ email to continue.",
          "noAccount": "No account yet? Click here to",
          "qqHint": "Enter your QQ number only. We'll add @qq.com and show your available sign-in options next.",
          "registration": {
            "errorMessage": "We couldn't create your account. Please check the email and try again.",
            "successMessage": "Check your email for the login link.",
            "successTitle": "Account created"
          },
          "signUp": "Sign up",
          "title": "Welcome"
        },
        "fields": {
          "email": "Email",
          "password": "Password"
        },
        "imageAlt": "Abstract wave pattern",
        "languageSwitch": {
          "label": "Change language"
        },
        "legal": {
          "agreement": "By clicking continue, you agree to our <terms>Terms of Service</terms> and <privacy>Privacy Policy</privacy>."
        },
        "methodsStep": {
          "description": "Choose how you want to continue.",
          "emailLink": "Send passwordless login link",
          "passkey": "Sign in with passkey",
          "separator": "OR",
          "signIn": "Sign in",
          "title": "Welcome",
          "useDifferentEmail": "Use a different email"
        }
      }
    }
  }
}
